In [1]:
import tensorflow as tf

In [2]:
scalar = tf.constant(7)

In [5]:
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
scalar.ndim

0

In [7]:
vector = tf.constant([10, 10])

In [8]:
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [9]:
vector.ndim

1

In [10]:
matrix = tf.constant([[10, 7],
                      [7, 10]])

In [11]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [12]:
matrix.ndim

2

In [13]:
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype = tf.float16)

In [19]:
changeable_tensor = tf.Variable([10, 7])

In [20]:
unchangeable_tensor = tf.constant([10, 7])

In [21]:
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [23]:
changeable_tensor[0] = 7

TypeError: 'ResourceVariable' object does not support item assignment

In [24]:
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [26]:
unchangeable_tensor[0] = 7

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [27]:
unchangeable_tensor[0].assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [2]:
random_1 = tf.random.Generator.from_seed(42)

In [4]:
random_1 = random_1.normal(shape = (3, 2))

In [5]:
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [6]:
random_2 = tf.random.Generator.from_seed(42)

In [7]:
random_2 = random_2.normal(shape = (3, 2))

In [8]:
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [9]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [2]:
# Shuffle a tensor

not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])

In [3]:
not_shuffled.ndim

2

In [4]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [10]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed = 42) #seed does not do what it should

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>